version: "3"


services:

  backend:
    build: ./Employees
    container_name: cogum-test
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./Employees/src:/app/src
    ports:
      - 3000:3000
      - 3030:3030
    environment:
      PORT: 3000
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: CogumDB
      DATABASE_URL: mysql://root:password@db:3306/CogumDB
    networks:
      - cogum_net

  db:
    container_name: cogum_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CogumDB
    volumes:
      - ./database-event:/var/lib/mysql
    networks:
      - cogum_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 9080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cogum_net

  redis-server: 
    image: 'redis'
    ports:
      - "4001:9081"
    networks:
      - cogum_net

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - cogum_net

  microservice01:
    build: ./SendEmail
    container_name: send-email-01
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./SendEmail/src:/app/src
    ports:
      - 3001:80
    networks:
      - cogum_net
      
  microservice02:
    build: ./SendEmail
    container_name: send-email-02
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./SendEmail/src:/app/src
    ports:
      - 3002:80
    networks:
      - cogum_net

  microservice03:
    build: ./SendEmail
    container_name: send-email-03
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./SendEmail/src:/app/src
    ports:
      - 3003:80
    networks:
      - cogum_net

volumes:
  prometheus-data:




networks:
  default:
    name: cogum_net
  cogum_net:
    driver: bridge