version: "3"


services:

  backend:
    build: ./Employees
    container_name: cogum-test
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./Employees/src:/app/src
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: CogumDB
      DATABASE_URL: mysql://root:password@db:3306/CogumDB

  db:
    container_name: cogum_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CogumDB
    volumes:
      - ./database-event:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 9080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  redis-server: 
    image: 'redis'
    ports:
      - "4001:9081"

  microservice01:
    build: ./SendEmail
    container_name: send-email-01
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./SendEmail/src:/app/src
    ports:
      - 3001:80
      
  microservice02:
    build: ./SendEmail
    container_name: send-email-02
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./SendEmail/src:/app/src
    ports:
      - 3002:80

  microservice03:
    build: ./SendEmail
    container_name: send-email-03
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./SendEmail/src:/app/src
    ports:
      - 3003:80





networks:
  default:
    name: cogum_net
  cogum_net:
    driver: bridge