global:
  scrape_interval: 30s
  evaluation_interval: 20s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          grupo: 'Prometheus'
  - job_name: Api
    static_configs:
      - targets: ['backend:3030']
        labels:
          grupo: 'Api'